In [2]:
import numpy as n

In [3]:
#q1
arr=n.array([1, 7, 13, 105])
print(f"the size of the memory occupied by the array is {arr.nbytes} bytes")


the size of the memory occupied by the array is 32 bytes


In [4]:
#q2

x = n.array([3, 5])
y = n.array([2, 5])

print(x)
print(y)
print("Comparison - greater")
print(n.greater(x, y))
print("Comparison - greater_equal")
print(n.greater_equal(x, y))
print("Comparison - less")
print(n.less(x, y))
print("Comparison - less_equal")
print(n.less_equal(x, y)) 

[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


In [5]:
#q3
z=n.zeros(10)
o=n.ones(10)
t=10*o
w=t*2
f=o*5
y=t*5
print(z,o,t,w,f,y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.] [20. 20. 20. 20. 20. 20. 20. 20. 20. 20.] [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.] [50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [6]:
#q4
arr=n.arange(30,71)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [7]:
#q5
ary=n.arange(50,96)
print(ary)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


In [8]:
#q6
ar2=n.arange(20,81,2)
print(f"even numbers",ar2)


even numbers [20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80]


In [9]:
#q7
ar1=n.arange(21,80,2)
print(f"odd numbers",ar1)

odd numbers [21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [10]:
#q8
arr1=n.random.randint(10,40,15)
print(arr1)

[10 20 30 12 20 25 31 14 27 19 16 35 27 27 28]


In [11]:
#q9
arr2=n.random.randint(30,50,10)
print(arr2)

[42 35 34 42 39 38 42 39 40 37]


In [12]:
#q10
arr3=n.random.randint(50,90,20)
print(arr3)

[54 76 53 55 57 65 65 73 52 66 70 76 84 55 70 79 81 54 66 77]


In [13]:
#q11
a=n.array([1,2,3,4,5])
b=n.array([10,20,30,40,50])
print(f"a=",a)
print(f"b=",b)
print(f"a+b=",a+b)
print(f"a-b=",a-b)
print(f"a*b=",a*b)
print(f"a/b",a/b)


a= [1 2 3 4 5]
b= [10 20 30 40 50]
a+b= [11 22 33 44 55]
a-b= [ -9 -18 -27 -36 -45]
a*b= [ 10  40  90 160 250]
a/b [0.1 0.1 0.1 0.1 0.1]


In [14]:
#q12
arr3=n.arange(10,22)
arr3=arr3.reshape([3,4])
print(arr3)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [15]:
#q13
i=n.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#q14
print(f"rows,columns")
print(arr3.shape)

rows,columns
(3, 4)


In [17]:
#q15
arr5=n.diag([1,2,3,4,5])
print(arr5)



[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [18]:
#q16
arr6=n.random.random((3,3,3))
print(arr6)

[[[0.02810738 0.32932934 0.44843102]
  [0.92739992 0.65063441 0.50163575]
  [0.21448633 0.18695903 0.82207982]]

 [[0.56589815 0.94367625 0.26776282]
  [0.80003329 0.42096188 0.29491439]
  [0.37043554 0.88275855 0.54178158]]

 [[0.84267542 0.18417298 0.27267234]
  [0.20711913 0.70108038 0.24475287]
  [0.23973555 0.42616632 0.27568022]]]


In [19]:
#q17
arr7=n.random.random((2,3,4))
print(arr7)

[[[0.80187128 0.70071028 0.77769985 0.79450707]
  [0.94289915 0.06374733 0.95326985 0.29462162]
  [0.10921629 0.33983741 0.13582799 0.48694497]]

 [[0.9492468  0.24021997 0.63444221 0.56664871]
  [0.09895846 0.56534444 0.65494466 0.12700788]
  [0.82242142 0.74404046 0.40226631 0.85305539]]]


In [21]:
#q18
l = [12.23, 13.32, 100, 36.32]
print(l)
arr8=n.array(l)
print(arr8)

[12.23, 13.32, 100, 36.32]
[ 12.23  13.32 100.    36.32]


In [22]:
x = n.arange(2, 11).reshape(3, 3)


print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [23]:
x= n.arange(12,38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [24]:
#q21
x = x[::-1]
print(x)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [25]:
a9=n.asfarray(a)
print(a9)

[1. 2. 3. 4. 5.]


In [29]:
#q23
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr = n.array(a)
print ("List: ", a)
print ("Array: ", arr)

List:  [1, 2, 3, 4, 5, 6, 7, 8, 9]
Array:  [1 2 3 4 5 6 7 8 9]


In [31]:
print("Element-wise remainder of division:")
print(n.remainder(arr, 5)) 

Element-wise remainder of division:
[1 2 3 4 0 1 2 3 4]


In [33]:
ar11=n.arange(21,50)
print(ar11)
print(n.remainder(ar11, 3)) 

[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
 45 46 47 48 49]
[0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
